// Digest storage and generation utilities
import { matchScoreEngine } from './preferences';
import jobsData from '../data/jobsData';

const DIGEST_KEY_PREFIX = 'jobTrackerDigest_';

export const digestStorage = {
  // Get today's date in YYYY-MM-DD format
  getTodayDate: () => {
    const today = new Date();
    return today.toISOString().split('T')[0];
  },

  // Get digest key for a specific date
  getDigestKey: (date) => {
    return `${DIGEST_KEY_PREFIX}${date}`;
  },

  // Get today's digest from localStorage
  getTodaysDigest: () => {
    const today = digestStorage.getTodayDate();
    const key = digestStorage.getDigestKey(today);
    try {
      const saved = localStorage.getItem(key);
      return saved ? JSON.parse(saved) : null;
    } catch (error) {
      console.error('Error reading digest from localStorage:', error);
      return null;
    }
  },

  // Save digest to localStorage
  saveDigest: (digest, date = null) => {
    const targetDate = date || digestStorage.getTodayDate();
    const key = digestStorage.getDigestKey(targetDate);
    try {
      localStorage.setItem(key, JSON.stringify(digest));
      return true;
    } catch (error) {
      console.error('Error saving digest to localStorage:', error);
      return false;
    }
  },

  // Check if digest exists for today
  hasTodaysDigest: () => {
    return digestStorage.getTodaysDigest() !== null;
  },

  // Clear all digests (for testing)
  clearAllDigests: () => {
    try {
      const keysToRemove = [];
      for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        if (key && key.startsWith(DIGEST_KEY_PREFIX)) {
          keysToRemove.push(key);
        }
      }
      keysToRemove.forEach(key => localStorage.removeItem(key));
      return true;
    } catch (error) {
      console.error('Error clearing digests:', error);
      return false;
    }
  }
};

// Digest generation logic
export const digestEngine = {
  // Generate today's digest based on user preferences
  generateTodaysDigest: (preferences) => {
    // Check if digest already exists for today
    const existingDigest = digestStorage.getTodaysDigest();
    if (existingDigest) {
      return existingDigest;
    }

    // Validate preferences
    if (!preferences) {
      throw new Error('Preferences are required to generate digest');
    }

    // Get all jobs
    const allJobs = [...jobsData];
    
    // Calculate match scores for all jobs
    const jobsWithScores = allJobs.map(job => ({
      ...job,
      matchScore: matchScoreEngine.calculateMatchScore(job, preferences)
    }));

    // Filter jobs with positive match scores
    const matchingJobs = jobsWithScores.filter(job => job.matchScore > 0);

    // Sort by matchScore (descending) then by postedDaysAgo (ascending)
    const sortedJobs = matchingJobs.sort((a, b) => {
      if (b.matchScore !== a.matchScore) {
        return b.matchScore - a.matchScore; // Higher match score first
      }
      return a.postedDaysAgo - b.postedDaysAgo; // More recent first
    });

    // Take top 10 jobs
    const topJobs = sortedJobs.slice(0, 10);

    // Create digest object
    const digest = {
      date: digestStorage.getTodayDate(),
      generatedAt: new Date().toISOString(),
      totalJobsConsidered: allJobs.length,
      matchingJobsFound: matchingJobs.length,
      jobs: topJobs,
      preferencesUsed: {
        roleKeywords: preferences.roleKeywords,
        preferredLocations: preferences.preferredLocations,
        preferredMode: preferences.preferredMode,
        experienceLevel: preferences.experienceLevel,
        skills: preferences.skills
      }
    };

    // Save to localStorage
    digestStorage.saveDigest(digest);
    
    return digest;
  },

  // Format digest for clipboard/email
  formatDigestForSharing: (digest) => {
    if (!digest || !digest.jobs || digest.jobs.length === 0) {
      return "No matching jobs found for today.";
    }

    const date = new Date(digest.date).toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    let formatted = `Top 10 Jobs For You — 9AM Digest\n`;
    formatted += `${date}\n\n`;
    formatted += `This digest was generated based on your preferences.\n\n`;

    digest.jobs.forEach((job, index) => {
      formatted += `${index + 1}. ${job.title}\n`;
      formatted += `   Company: ${job.company}\n`;
      formatted += `   Location: ${job.location}\n`;
      formatted += `   Experience: ${job.experience}\n`;
      formatted += `   Match Score: ${job.matchScore}%\n`;
      formatted += `   Apply: ${job.applyUrl}\n\n`;
    });

    formatted += "Demo Mode: Daily 9AM trigger simulated manually.\n";
    formatted += "This digest was generated by the Job Notification Tracker.";

    return formatted;
  },

  // Get score badge class based on score
  getScoreBadgeClass: (score) => {
    if (score >= 80) return 'score-green';
    if (score >= 60) return 'score-amber';
    if (score >= 40) return 'score-neutral';
    return 'score-grey';
  },
  
  // Get score badge text
  getScoreBadgeText: (score) => {
    return `${score}% match`;
  }
};